# Re-generate the site when files are modified
auto: true

# Serve everything under _site
server: true

# Enable Pygments
pygments: true

# Produce an index for related posts
lsi: true

# Exclude some files:
exclude: CNAME, README.rst
